apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.graphAnalyzerApi.name }}
  labels:
    app: {{ .Values.graphAnalyzerApi.name }}
spec:
  type: ClusterIP
  ports:
    - name: "{{ .Values.graphAnalyzerApi.name }}-http"
      port: 8080
      protocol: TCP
      targetPort: {{ .Values.graphAnalyzerApi.config.appServerPort }}
  selector:
    app: {{ .Values.graphAnalyzerApi.name }}