{{- if .Values.graphAnalyzerDataCollector.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.graphAnalyzerDataCollector.name }}-secret"
type: Opaque
data:
  NEO4J_USER: {{ .Values.config.neo4j.neo4jUser | b64enc }}
  NEO4J_PASSWORD: {{ .Values.config.neo4j.neo4jPassword | b64enc }}
{{- end }}  